feat: parameter processing + custom naming
onecx/onecx-nx-plugins pull request #101
Opened 2024-06-10 09:50 UTC by BenjaminPabst

**Parameter Processing & API-First Option + Fixes**

This PR adds a new system of parameter processing as well as the option for custom naming for search & details when generating.

**Parameter Processing**
The generator (nx-plugin) for details and search are extended with a new parameter processing.
This means, that options can be defined that are either provided by CLI Parameters (`--<key> <value>`) or through an interactive CLI-Interface by the developer.
![image](https://github.com/onecx/onecx-nx-plugins/assets/166110368/59bc1b01-d1cb-4f1d-92f4-614e23bb30f9)

The system is designed in a generic manner and can be easily extended with more features in the future.
Currently, it supports boolean, number, text input and the option to display a select to the user (to pick an option from).
In addition, it supports rule-based paths (as long as the required input was provided before).
The library enquirer is used for the interactive part, yargs is used to parse parameters beforehand if provided, allowing a full non-interactive interaction as well.

**API-Renaming Option**
Both search & details were extended with an option to rename the generated API Models when necessary. This can allow an easier adaption to legacy BFFs.

**Fixes**
In addition, some more issues have been fixed, as unused dependencies etc.

**Tests**
The tests were extended to also test the generation with custom naming.

2024-06-11 07:44 UTC, anninowak commented on nx-plugin/src/generators/search/generator.ts
> +    key: 'dataObjectName',
Warum hast du dich für dataObjectName entschieden?

2024-06-11 07:58 UTC, BenjaminPabst commented on nx-plugin/src/generators/search/generator.ts
> +    key: 'dataObjectName',
Da eine Suche sich ja primär um ein Daten-Objekt (Buch, Person, Vergünstigung, Theme, etc.) dreht, fand ich den Begriff am treffendsten. Es geht ja um den Namen dieses Daten-Objekts (bzw. das interface).

2024-06-13 07:23 UTC, anninowak requested changes

2024-06-13 07:23 UTC, anninowak commented on README.md
> +- `showIf(values)`: an callback that needs to return whether the respective option should be shown or not. Values ar all inputs that were provided before
Values or all inputs

2024-06-13 08:12 UTC, anninowak approved these changes

2024-06-13 08:13 UTC, merged