feat: migrate to webcomponents
onecx/onecx-nx-plugins pull request #114
Opened 2024-07-17 08:12 UTC by BenjaminPabst

2024-07-17 08:35 UTC, markuczy commented on nx-plugin/src/generators/angular/files/helm/values.yaml
> +          tagName: <%= remoteModuleFileName %>-webcomponent
Looks different than for tenant-ui (which is basing on generator). Make sure its correct for whatever operator those should use (https://github.com/onecx/onecx-tenant-ui/commit/1586479ff7da5b391eb4f62e4d1680aab1f7b640#diff-81801117ec01136c8a49bfcd42af8e104f4efad1f2daccda9da9d960eaad5279R13)

2024-07-17 08:35 UTC, markuczy commented on nx-plugin/src/generators/angular/files/src/app/__remoteModuleFileName__-app.remote.module.ts.template
> +import { AppEntrypointComponent } from './app-entrypoint.component';
Did You add required packages somewhere? You should have:

- @angular/elements
- @onecx/angular-auth (most likely)
- @onecx/angular-webcomponents
- @webcomponents/webcomponentsjs
Maybe some more (not sure tho)

2024-07-17 08:35 UTC, markuczy commented on nx-plugin/src/generators/angular/files/src/app/__remoteModuleFileName__-app.remote.module.ts.template
> +import { AppEntrypointComponent } from './app-entrypoint.component';
Also You need to add the `node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js` to the build

2024-07-17 08:35 UTC, markuczy commented on nx-plugin/src/generators/angular/files/src/app/__remoteModuleFileName__-app.remote.module.ts.template
> +  }
You should use new approach with createAppEntrypoint

2024-07-17 08:35 UTC, markuczy commented on nx-plugin/src/generators/angular/generator.ts
> +  const oneCXLibVersion = '^4.41.0';
Use 4.22.0

2024-07-17 08:35 UTC, markuczy commented on nx-plugin/src/generators/details/steps/feature-routes.step.ts
> +        `routes: Routes = [ { matcher: startsWith('details/:id'), component: ${className}DetailsComponent, pathMatch: 'full' },`
This most likely will not work :/

2024-07-17 08:35 UTC, markuczy commented on nx-plugin/src/generators/details/steps/feature-routes.step.ts
> +        `routes: Routes = [ { matcher: startsWith('details/:id'), component: ${className}DetailsComponent, pathMatch: 'full' },`
You will need to create Your own matcher for this

2024-07-17 14:08 UTC, markuczy approved these changes

2024-07-18 06:31 UTC, SchettlerKoehler requested changes

2024-07-18 06:31 UTC, SchettlerKoehler commented on nx-plugin/src/generators/angular/files/webpack.config.js.template
> +    '@onecx/angular-accelerator': {
`@onecx/webcomponents` should also be here

2024-07-18 06:31 UTC, SchettlerKoehler commented on nx-plugin/src/generators/delete/steps/search-tests.step.ts
> +    if (!htmlContent.includes(`import { PrimeIcons } from 'primeng/api';`)) {
We are always doing organize imports at the end, so duplicate imports will be removed

2024-07-18 07:33 UTC, BenjaminPabst commented on nx-plugin/src/generators/delete/steps/search-tests.step.ts
> +    if (!htmlContent.includes(`import { PrimeIcons } from 'primeng/api';`)) {
had that weirdly crashing my tests once, but now it works again, so removed the check.

2024-07-18 07:48 UTC, SchettlerKoehler approved these changes

2024-07-18 07:49 UTC, merged