feat: migrate to angular 18
onecx/onecx-nx-plugins pull request #126
Opened 2024-08-29 12:38 UTC by BenjaminPabst

2024-08-30 10:00 UTC, BenjaminPabst commented on nx-plugin/src/generators/angular/generator.ts
> +      '@nx/plugin': '^19.5.7',
migration made it necessary to set a lot of versions fixed somehow

2024-08-30 10:00 UTC, BenjaminPabst commented on nx-plugin/src/generators/angular/generator.ts
> +    delete json.targets.build.options.browser;
normally I though this should be fixed with the nx upgrade, but it still seems like it generates browser instead of main somehow

2024-08-30 10:45 UTC, SchettlerKoehler requested changes

2024-08-30 10:45 UTC, SchettlerKoehler commented on nx-plugin/src/generators/create-update/steps/search-tests.step.ts
> +      const rowActionButtons = await dataTable!.getActionButtons();
When you are doing it like this the test will with 'can not read getActionButtons of undefined'. Which is not a good thin because it could be hard to find. You should do it with ?. To make it work, you will then also need a question mark in line 49.

2024-08-30 10:45 UTC, SchettlerKoehler commented on nx-plugin/src/generators/delete/steps/search-tests.step.ts
> +        const rowActionButtons = await dataTable!.getActionButtons();
Same here

2024-08-30 10:45 UTC, SchettlerKoehler commented on nx-plugin/src/generators/details/steps/search-tests.step.ts
> +      const rowActionButtons = await dataTable!.getActionButtons();
Same here

2024-08-30 10:45 UTC, SchettlerKoehler commented on nx-plugin/src/generators/search/files/ngrx/src/app/__featureFileName__/pages/__featureFileName__-search/__featureFileName__-search.component.spec.ts.template
> +    const rows = await dataTable!.getRows();
Same here

2024-09-03 05:04 UTC, SchettlerKoehler requested changes

2024-09-03 05:04 UTC, SchettlerKoehler commented on nx-plugin/src/generators/angular/generator.ts
> +      primeng: '17.18.8', // 15.2.1 is the last version where the tests are running!!!
Remove comment

2024-09-03 06:44 UTC, merged