feat: details feature harness and tests added
onecx/onecx-nx-plugins pull request #51
Opened 2024-04-03 10:56 UTC by markuczy

2024-04-04 05:17 UTC, SchettlerKoehler requested changes
Please also make headerLabels an observable: https://github.com/onecx/onecx-nx-plugins/blob/main/nx-plugin/src/generators/details/files/ngrx/src/app/__featureFileName__/pages/__featureFileName__-details/__featureFileName__-details.component.ts.template#L24
like it is done here with the headerActions: https://github.com/onecx/onecx-nx-plugins/blob/main/nx-plugin/src/generators/search/files/ngrx/src/app/__featureFileName__/pages/__featureFileName__-search/__featureFileName__-search.component.ts.template#L43
The reason for this is that the values for headerLabels will come from the ViewModel in most cases and setting them should be as easy as possible

2024-04-04 05:17 UTC, SchettlerKoehler commented on nx-plugin/src/generators/details/files/ngrx/src/app/__featureFileName__/pages/__featureFileName__-details/__featureFileName__-details.harness.ts.template
> +  getPageHeader = this.locatorFor(PageHeaderHarness);
getHeader

2024-04-04 07:20 UTC, markuczy commented
@SchettlerKoehler In Details Page component headerLabels and headerActions should now be observables.

2024-04-08 06:30 UTC, SchettlerKoehler approved these changes

2024-04-09 09:11 UTC, merged